added more error checking

diff --git a/movedata b/movedata
--- a/movedata
+++ b/movedata
@@ -12,29 +12,50 @@ touch $logfile
 errorlogfile="/data/home/copy_dir/tmp/movedataerrorlog_$today"
 touch $errorlogfile
 
+function chk {
+  if [ $? -ne 0 ] ; then
+    /bin/echo "ERROR: $1"
+    exit 1
+  fi
+}
+
 function move-to-cmc-subdir {
 if [ -d "/data/home/$1/cmc" ]
 then
-   mv /data/home/copy_dir/$1/ /data/home/$1/cmc
+   if [ $1 == lil997 ]
+   then
+      /bin/mv -f /data/home/copy_dir/llixiang/* /data/home/lil997/cmc/
+      chk "can not move data for llixiang" >> $errorlogfile
+      /bin/rm -r /data/home/copy_dir/llixiang
+      chk "can not remove directory for llixiang" >> $errorlogfile
+   else
+      /bin/mv -f /data/home/copy_dir/$1/* /data/home/$1/cmc/
+      chk "can not move data for $1" >> $errorlogfile
+      /bin/rm -r /data/home/copy_dir/$1/
+      chk "can not remove directory for $1" >> $errorlogfile
+   fi
    chown -Rh $1 /data/home/$1/cmc
-   echo "move data and change owner for $1" >> $logfile
+   chk "can not chown for $1" >> $errorlogfile
+   /bin/echo "move data and change owner for $1" >> $logfile
 else
-   echo "/data/home/$1/cmc doesn't exist" >> $errorlogfile
+   /bin/echo "/data/home/$1/cmc doesn't exist" >> $errorlogfile
 fi
 }
 
 # fix permission
-find /data/home/copy_dir -type d -print0 | xargs -0 chmod 700 
-find /data/home/copy_dir -type f -print0 | xargs -0 chmod go-rwx
+/bin/find /data/home/copy_dir -type d -print0 | /bin/xargs -0 chmod 700 
+/bin/find /data/home/copy_dir -type f -print0 | /bin/xargs -0 chmod go-rwx
 
 
 while IFS= read -r THELINE; do
-  if [ "$THELINE" == "llixiang" ]
-  then
-     # nsid for llixiang is lil997 
-     move-to-cmc-subdir lil997
-  else
-     # normal nsid
-     move-to-cmc-subdir $THELINE
+  if [ -n "$THELINE" ]; then
+     if [ "$THELINE" == "llixiang" ]
+     then
+        # nsid for llixiang is lil997 
+        move-to-cmc-subdir lil997
+     else
+        # normal nsid
+        move-to-cmc-subdir $THELINE
+     fi
   fi
 done < /data/home/copy_dir/tmp/cmc-home
